// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

public type Message_function record {
    string name?;
    record {} arguments?;
};

public type ShowResponse record {
    string license?;
    string modelfile?;
    string parameters?;
    string template?;
    string parent_model?;
    string format?;
    TagsResponse_details details?;
};

public type Message record {
    "user"|"assistant"|"system" role;
    string content;
    string[] images?;
    Message_tool_calls[] tool_calls?;
};

public type CreateRequest record {
    # Name of the model to create
    string name;
    # Model file contents
    string modelfile;
    # Whether to stream the response
    boolean 'stream?;
};

public type CreateResponse record {
    # Status of model creation
    string status?;
};

public type TagsResponse_details record {
    string family?;
    string[] families?;
    int parameter_count?;
    string quantization_level?;
};

public type PullRequest record {
    string name;
    boolean insecure?;
    boolean 'stream?;
};

public type ChatResponse record {
    string model?;
    string created_at?;
    Message message?;
    boolean done?;
    # Reason generation completed
    string done_reason?;
    int total_duration?;
    int load_duration?;
    int prompt_eval_count?;
    int prompt_eval_duration?;
    int eval_count?;
    int eval_duration?;
};

public type TagsResponse record {
    TagsResponse_models[] models?;
};

public type ChatRequest record {
    string model;
    Message[] messages;
    "json" format?;
    record {} options?;
    boolean 'stream?;
    # Duration to keep model loaded
    string keep_alive?;
};

public type EmbeddingsRequest record {
    string model;
    string prompt;
    record {} options?;
    # Duration to keep model loaded
    string keep_alive?;
};

public type TagsResponse_models record {
    string name?;
    string modified_at?;
    int size?;
    string digest?;
    TagsResponse_details details?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    ClientHttp1Settings http1Settings?;
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings?;
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 60;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache?;
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits?;
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type Message_tool_calls record {
    Message_function 'function?;
};

public type EmbeddingsResponse record {
    decimal[] embedding?;
};

public type CopyRequest record {
    string 'source;
    string destination;
};

public type ShowRequest record {
    string name;
};

public type GenerateResponse record {
    string model?;
    string created_at?;
    string response?;
    boolean done?;
    # Reason generation completed
    string done_reason?;
    int[] context?;
    int total_duration?;
    int load_duration?;
    int prompt_eval_count?;
    int prompt_eval_duration?;
    int eval_count?;
    int eval_duration?;
};

# Proxy server configurations to be used with the HTTP client endpoint.
public type ProxyConfig record {|
    # Host name of the proxy server
    string host = "";
    # Proxy server port
    int port = 0;
    # Proxy server username
    string userName = "";
    # Proxy server password
    @display {label: "", kind: "password"}
    string password = "";
|};

public type GenerateRequest record {
    # Name of the model to use
    string model;
    # The prompt to generate completion for
    string prompt;
    # Format of the response
    "json" format?;
    # Additional model parameters
    record {} options?;
    # System prompt
    string system?;
    # Custom prompt template
    string template?;
    # Previous context for continuation
    int[] context?;
    # Whether to stream the response
    boolean 'stream?;
    # Whether to return raw response
    boolean raw?;
    # Duration to keep model loaded
    string keep_alive?;
};

public type PullResponse record {
    string status?;
    string digest?;
    int total?;
    int completed?;
};

# Provides settings related to HTTP/1.x protocol.
public type ClientHttp1Settings record {|
    # Specifies whether to reuse a connection for multiple requests
    http:KeepAlive keepAlive = http:KEEPALIVE_AUTO;
    # The chunking behaviour of the request
    http:Chunking chunking = http:CHUNKING_AUTO;
    # Proxy server related options
    ProxyConfig proxy?;
|};

public type DeleteRequest record {
    string name;
};

public type PushRequest record {
    string name;
    boolean insecure?;
    boolean 'stream?;
};

public type PushResponse record {
    string status?;
    string digest?;
    int total?;
    int completed?;
};
